jobs:
  documentation:
    if: github.repository == 'deepjavalibrary/djl'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 17
    - continue-on-error: true
      name: Set up Python3
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      name: Install CN fonts
      run: sudo apt-get update && sudo apt-get install fonts-arphic-uming
    - continue-on-error: true
      name: install Python Dependencies
      run: pip3 install nbconvert mkdocs==1.4.3 mkdocs-exclude mknotebooks mkdocs-material
        jupyter Pygments Markdown
    - continue-on-error: true
      name: Install IJava kernel
      run: 'git clone https://github.com/frankfliu/IJava.git

        cd IJava/

        ./gradlew installKernel

        '
    - continue-on-error: true
      name: checkout repo
      uses: actions/checkout@v4
    - continue-on-error: true
      name: add mybinder link
      run: 'python3 tools/scripts/add_online_runner.py

        '
    - continue-on-error: true
      name: clone demos
      run: 'cd docs

        git clone https://github.com/deepjavalibrary/djl-demo.git demos

        '
    - continue-on-error: true
      name: clone serving
      run: 'cd docs

        git clone https://github.com/deepjavalibrary/djl-serving.git serving

        '
    - continue-on-error: true
      name: run Notebooks
      run: 'cd docs/demos/jupyter

        bash test_notebook.sh

        '
    - continue-on-error: true
      name: build docs
      run: 'cd docs

        export DJL_DISABLE_PROGRESS_BAR=true

        mkdocs build --site-dir ../../site

        '
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: us-east-2
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Copy files to S3 with the AWS CLI
      run: 'aws s3 sync ../site s3://djl-ai/documentation/nightly --delete

        aws cloudfront create-invalidation --distribution-id E733IIDCG0G5U --paths
        "/*"

        '
name: Docs
on:
  repository_dispatch:
    types: trigger-ga___docs.yml
