jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 17
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: ~/.gradle/caches
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: us-east-2
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - continue-on-error: true
      name: Copy files to S3
      run: './gradlew :engines:pytorch:pytorch-native:uploadS3

        PYTORCH_VERSION=$(cat gradle.properties | awk -F ''='' ''/pytorch_version/
        {print $2}'')

        aws cloudfront create-invalidation --distribution-id E371VB8JQ6NRVY --paths
        "/pytorch/${PYTORCH_VERSION}/*"

        '
name: Native S3 PyTorch
on:
  repository_dispatch:
    types: trigger-ga___native_s3_pytorch.yml
