jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Apache MXNet repository
      uses: actions/checkout@v4
      with:
        ref: 1.9.1
        repository: apache/incubator-mxnet
        submodules: recursive
    - continue-on-error: true
      name: Install Dependencies
      run: 'brew install nasm automake ninja libtool

        '
    - continue-on-error: true
      name: Build
      run: 'git --version

        clang --version

        CMAKE_STATICBUILD=1 ./tools/staticbuild/build.sh cpu

        '
    - continue-on-error: true
      name: Upload libmxnet.dylib
      uses: actions/upload-artifact@v3
      with:
        name: libmxnet.dylib
        path: build/libmxnet.dylib
name: Native Build MXNet OSX
on:
  repository_dispatch:
    types: trigger-ga___native_build_mxnet_osx.yml
