jobs:
  build:
    env:
      NDK_VERSION: 21.1.6352462
      PYTORCH_VERSION: 2.1.2
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 17
    - continue-on-error: true
      name: Set up Python3
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      name: clone pytorch
      run: 'git clone https://github.com/pytorch/pytorch android_pytorch_tmp -b "v${PYTORCH_VERSION}"
        --recursive

        '
    - continue-on-error: true
      name: install Python Dependencies
      run: pip install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions
    - continue-on-error: true
      name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install
        "ndk;${NDK_VERSION}"
    - continue-on-error: true
      name: build android
      run: 'export ANDROID_NDK=${ANDROID_SDK_ROOT}/ndk/${NDK_VERSION}

        export ANDROID_ABI=${{ matrix.format }}

        cd android_pytorch_tmp

        BUILD_LITE_INTERPRETER=0 ./scripts/build_android.sh

        cd build_android

        zip -r ${{ matrix.format }}_native.zip install/include lib

        '
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: us-east-2
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - continue-on-error: true
      name: Copy files to S3 with the AWS CLI
      run: 'aws s3 cp android_pytorch_tmp/build_android/${{ matrix.format }}_native.zip
        s3://djl-ai/publish/pytorch/${PYTORCH_VERSION}/android_native/

        aws cloudfront create-invalidation --distribution-id E371VB8JQ6NRVY --paths
        "/pytorch/${PYTORCH_VERSION}/android_native*"

        '
    strategy:
      matrix:
        format:
        - armeabi-v7a
        - arm64-v8a
        - x86
        - x86_64
name: Native S3 PyTorch Android
on:
  repository_dispatch:
    types: trigger-ga___native_s3_pytorch_android.yml
