jobs:
  build:
    if: github.repository == 'deepjavalibrary/djl'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 17
    - continue-on-error: true
      name: Gradle cache
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        disable-animations: true
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio
          -no-boot-anim -camera-back none
        force-avd-creation: false
        script: cd android/core && ./gradlew cAT
    strategy:
      matrix:
        api-level:
        - 26
name: Continuous Android
on:
  repository_dispatch:
    types: trigger-ga___nightly_android.yml
