jobs:
  noResponse:
    if: github.repository == 'deepjavalibrary/djl'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: lee-dohm/no-response@v0.5.0
      with:
        daysUntilClose: 30
        token: ${{ github.token }}
name: No Response
on:
  repository_dispatch:
    types: trigger-ga___no_response.yml
