jobs:
  release-android:
    if: github.repository == 'deepjavalibrary/djl'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 17
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: ~/.gradle/caches
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ORG_GRADLE_PROJECT_ossrhPassword
          }}
        ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ORG_GRADLE_PROJECT_ossrhUsername
          }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword
          }}
      if: ${{ github.event.inputs.mode == '' || github.event.inputs.mode == 'snapshot'
        }}
      name: publish android core and pytorch-native to sonatype
      run: './gradlew :pytorch-native:assemble

        ./gradlew publish -Psnapshot

        '
      working-directory: android
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ORG_GRADLE_PROJECT_ossrhPassword
          }}
        ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ORG_GRADLE_PROJECT_ossrhUsername
          }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword
          }}
      if: ${{ github.event.inputs.mode == 'staging' }}
      name: publish android core and pytorch-native to sonatype
      run: './gradlew :pytorch-native:assemble

        ./gradlew publish -Pstaging

        '
      working-directory: android
name: Publish Android packages
on:
  repository_dispatch:
    types: trigger-ga___publish_android_packages.yml
