jobs:
  publish-job-success-to-cloudwatch:
    if: ${{ github.event.workflow_run.event == 'schedule' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::185921645874:role/djl-github-cloudwatch-ci-metrics
    - continue-on-error: true
      env:
        CONCLUSION: ${{ github.event.workflow_run.conclusion }}
        REPO_NAME: ${{ github.event.workflow_run.repository.name }}
        WORKFLOW_NAME: ${{ github.event.workflow_run.display_title }}
      name: Publish Job Success Metric
      run: "workflow_name=$(echo \"$WORKFLOW_NAME\" | tr -d ' ')\nmetric_name=\"${REPO_NAME}-${workflow_name}-Failure\"\
        \nfailedBuild=$([ \"$CONCLUSION\" == \"success\" ]; echo $?)\naws cloudwatch\
        \ put-metric-data --namespace GithubCI \\\n  --metric-name \"$metric_name\"\
        \ \\\n  --value $failedBuild \\\n  --unit Count\n"
name: Publish Job Success Metric to CloudWatch
on:
  repository_dispatch:
    types: trigger-ga___publish-job-success.yml
permissions:
  contents: read
  id-token: write
